//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class baza1Entities : DbContext
    {
        public baza1Entities()
            : base("name=baza1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Services_> Services_ { get; set; }
        public virtual DbSet<ServicesImages> ServicesImages { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
